### ISSUE TITLE
Warning: Received `true` for a non-boolean attribute `uppercase`.

### ISSUE THREAD

**Issue by dinaomari90** [GeekyAnts/native-base-docs#103]
Im getting this error when i run` npm start `

> Warning: Received `true` for a non-boolean attribute `uppercase`.
![native](https://user-images.githubusercontent.com/38206630/41199147-f64b531a-6c95-11e8-92af-f0d34e9b0b51.png)
![err](https://user-images.githubusercontent.com/38206630/41199148-ff3e1b10-6c95-11e8-9d2b-be5ab04d2262.png)

**Comment by SupriyaKalghatgi** [comment]
This is not the correct place
Closing this
