### ISSUE TITLE
flex not working on DeckSwiper component

### ISSUE THREAD

**Issue by gregoireLem** [GeekyAnts/native-base-docs#120]
My deck swipper component is in the view with red border. It has  flex:1, but this is not working (see the picture).

<img width="377" alt="capture d ecran 2018-07-21 a 12 48 51" src="https://user-images.githubusercontent.com/31652880/43034891-220075ca-8ce5-11e8-8761-ab2501b69745.png">

`<DeckSwiper
              style={{flex:1, borderWidth:10, borderColor:'green'}}
              looping = {false}
              dataSource={this.getStack()}
              renderItem={item =>
              
      <Card style={{  paddingTop:50,flex:1, backgroundColor: 'white', alignItems: 'center', borderRadius: 20, borderWidth:10, borderColor:'yellow'}}>
                              <CardItem style={{backgroundColor: 'transparent'}}>
                                <View style={styles.titleText}>
                                  <Text style={styles.textTitle}>{item.name}</Text>
                                </View>
                              </CardItem>
      </Card>
}
              onSwipeRight={() => this.updateDeckSize()}
              onSwipeLeft={() => this.updateDeckSize()}
/>`

Thanks for helping

**Comment by suvenduchhatoi** [comment]
@gregoireLem Plz open your issue in https://github.com/GeekyAnts/NativeBase/issues in ISSUE_TEMPLATE format
