### ISSUE TITLE
Unable to change background color globally ?

### ISSUE THREAD

**Issue by nainishmodi** [GeekyAnts/native-base-docs#125]
i want to change this background color globally..how can i change this color so i can replace my custom color..

![capture](https://user-images.githubusercontent.com/17999172/43753397-2a39fac2-9a23-11e8-974f-bcaffeecf2f2.PNG)

**Comment by suvenduchhatoi** [comment]
@nainishmodi Plz open your issue in https://github.com/GeekyAnts/NativeBase/issues in ISSUE_TEMPLATE format
