### ISSUE TITLE
Drawer.md is not up-to-date

### ISSUE THREAD

**Issue by fuj1w4r4** [GeekyAnts/native-base-docs#141]
Hi there, apparently Drawer.md is not up-to-date. the version of native-base i am using is 2.8.1

		interface Drawer {
			acceptDoubleTap?: boolean;
			acceptPan?: boolean;
			acceptTap?: boolean;
			captureGestures?: boolean;
			children?: any;
			open?: boolean;
			closedDrawerOffset?: number;
			content?: any;
			deviceScreen?: ReactNative.ScaledSize;
			disabled?: boolean;
			initializeOpen?: boolean;
			negotiatePan?: boolean;
			onClose?: Function;
			onCloseStart?: Function;
			onOpen?: Function;
			onOpenStart?: Function;
			openDrawerOffset?: number;
			openDrawerThreshold?: number;
			panCloseMask?: number;
			panOpenMask?: number;
			panStartCompensation?: boolean;
			relativeDrag?: boolean;
			side?: "left" | "right";
			styles?: DrawerStyles;
			tapToClose?: boolean;
			tweenDuration?: number;
			tweenEasing?: string;
			tweenHandler?: Function;
			type?: "overlay" | "static" | "displace";
		}

please advise.

**Comment by suvenduchhatoi** [comment]
@fuj1w4r4 Do you mean all props defined in interface are not in config table? See we have given link for the replacing component of Drawer https://github.com/root-two/react-native-drawer ...You can get the list of props and their working mechanism there...
