### ISSUE TITLE
 Better use of Ionicons by specific platform

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/native-base-docs#143]
https://github.com/GeekyAnts/NativeBase/issues/2361

**Comment by suvenduchhatoi** [comment]
@italomlp check latest version docs... They have been updated

**Comment by italomlp** [comment]
I think that it still not clear. Maybe the name prop from Icon doc have something like:

Property | Default | Option | Description
-- | -- | -- | --
name | - | - | Name of the icon. (If Ionicons is your font choice, then use icon name without preffix. E.g.: for `md-home` and `ios-home`, you can use `name="home"`, the `md-` or `ios-` preffix will be added automatically.)
