### ISSUE TITLE
Documentation is inadequate

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/native-base-docs#146]
https://github.com/GeekyAnts/NativeBase/issues/2410

**Comment by SupriyaKalghatgi** [comment]
@kaitlynbrown NativeBase Docs is open source repo
You can contribute

**Comment by kaitlynbrown** [comment]
I'm not sure how I'm supposed to contribute information that I don't yet have. Do you expect me to go digging through the nativebase code to find out how things work and then write documentation for it? Wouldn't it make a lot more sense for the people who wrote the components and already know how they work to provide the documentation?

**Comment by suvenduchhatoi** [comment]
@kaitlynbrown We have been constantly updating docs and adding new features with every new version of docs, thereby trying to solve issues. Check latest versions of docs....
