### ISSUE TITLE
DeckSwiper doesn't respect datasource changes at the renderItem level

### ISSUE THREAD

**Issue by MaciekLeks** [GeekyAnts/native-base-docs#147]
Context: NB v2.8.1

For the given _dataSource_  array (e.g. `ds`) if the change important to the component user appears in one of the _renderItem's_ properties (e.g. `peoperty1`) and the whole system respect it, the only component which does not respect the change is Deck Swiper, e.g.
```javascript
const ds= [
  {
     property1: false,
     ...
   },
   { //active card
     property1: false, // -> true value when the state changes
     ...
   },
   ... 
];
```
I work with redux and I follow the Redux Immutable Data Modification Patterns.  Just before `render` the `ds` is properly changed, but Deck Swiper doesn't want to show it on active card. To make the change visible, I have to swipe the card first, but it's not an option for an user experience.

**Comment by suvenduchhatoi** [comment]
@MaciekLeks Please post your issue here https://github.com/GeekyAnts/NativeBase/issues in ISSUE_TEMPLATE format
