### ISSUE TITLE
Component Docs Are Practically Unusable On Mobile And Smaller Screens

### ISSUE THREAD

**Issue by ecbrodie** [GeekyAnts/native-base-docs#183]
This issue is to report a significant usability concern I have with your [Components Documentation](https://docs.nativebase.io/Components.html). I find this documentation to be **practically unusable** on mobile devices and smaller screens. The main two symptoms I am running into are:

* The DOM of the page is HUGE, which can cause very high load times for devices with lower memory (a mobile-specific concern)
* The device preview pane will overlap the documentation text as the screen size gets smaller. Since the text does not wrap around the device preview, the left sidebar cannot be resized, and the device preview cannot be hidden, the documentation becomes completely unreadable. Definitely a concern on mobile, but it's even a problem on my 13 inch Macbook Air.

I am now forced to be at my home or office workstation with an external monitor connected in order to read Native-Base documentation. That is of course unreasonable, as there are many other places I wish to consume this documentation on a smaller screen (ex: while commuting to work, at the coffee shop, or even just on my laptop).

Without being able to easily consume documentation for a framework, it becomes hard to continue using the framework. I think it would be wise for this issue to be given careful consideration. Even just something as simple as adding a show/hide toggle to the device preview may be enough to appease most of this issue's concerns.

**Comment by ecbrodie** [comment]
@SupriyaKalghatgi @suvenduchhatoi I am requesting attention on this issue please.

**Comment by sanketsahusoft** [comment]
@ecbrodie We have considered this. @SupriyaKalghatgi will get back to you.

**Comment by SupriyaKalghatgi** [comment]
@ecbrodie I will look into this and get back to you
Will take some time though

**Comment by SupriyaKalghatgi** [comment]
@ecbrodie The latest docs is live with 2.12.0 and usable on smaller devices

**Comment by ecbrodie** [comment]
@SupriyaKalghatgi I have tried out the updated docs on my mobile device and here's my feedback:

* The webpage on mobile has gone from *completely unusable* to *barely usable*
* I am now able to read the text of the desired component I'm looking up about 50% of the time. Half the time, the webpage crashes due to the DOM still being extremely large and thus eating up all my device's memory. The other half of the time, I still experience severely degraded performance (ex, large page load times, reading about a second component will cause the page to crash)
* I still see the *Device Preview Widget* load on the mobile page, but then disappear a few seconds later. I think that this approach still causes issues. The device preview may still be loaded into the page, just not visible. This could be eating up into the DOM size and thus hurting performance.
* Why not split this one giant HTML page into multiple smaller pages? Or, just load each component' section lazily as requested?

Overall, while my issue may be minimally fixed, I don't think it's enough to consider Native Base's documentation to be sufficient for mobile devices.
