### ISSUE TITLE
I can't make this work!!

### ISSUE THREAD

**Issue by manodupont** [GeekyAnts/native-base-docs#23]
So, native-base-theme has been copied great.

I set my StyleProvider , then thats it ? right ? i should have a theme right ?

**Comment by manodupont** [comment]
It says,

```
<StyleProvider style={getTheme(material)}>
            <Container>
                    <Content>
                        <Text>
                            I have changed the text color.
                        </Text>
                    </Content>
            </Container>
          </StyleProvider>
```

But what about this one ?
https://nativebase.io/docs/v0.4.6/customize

Both are not showing any changes on rendering.

So, when using StyleProvider, should ALL my components be themed ?

**Comment by Jasbir23** [comment]
Please refer to the new updated NativeBase docs [here](http://docs.nativebase.io/)
