### ISSUE TITLE
[SUGGESTION] [DOCS] Please use real image for docs

### ISSUE THREAD

**Issue by shivrajkumar** [GeekyAnts/native-base-docs#38]
https://github.com/GeekyAnts/NativeBase/issues/1055

**Comment by mnlbox** [comment]
@shivrajkumar another page is here:
https://docs.nativebase.io/Components.html#list-def-headref
code:
```
<Container>
        <Header />
        <Content>
          <List>
            <ListItem>
              <Text>Simon Mignolet</Text>
            </ListItem>
            <ListItem>
              <Text>Nathaniel Clyne</Text>
            </ListItem>
            <ListItem>
              <Text>Dejan Lovren</Text>
            </ListItem>
          </List>
        </Content>
      </Container>
```
but it's image:
![list-basic](https://user-images.githubusercontent.com/25859075/30309880-e0052cca-97a2-11e7-8f6c-2e4c418b96e3.png)

**Comment by SupriyaKalghatgi** [comment]
Check latest docs

**Comment by mnlbox** [comment]
@SupriyaKalghatgi I check and unfortunately still NativeBase contain fake images in docs.

**Comment by mnlbox** [comment]
@SupriyaKalghatgi Any news?
