### ISSUE TITLE
Repeated paragraph 

### ISSUE THREAD

**Issue by mitramejia** [GeekyAnts/native-base-docs#41]
A paragraph is repeated at https://docs.nativebase.io/Customize.html#Customize

![customize_ _nativebase](https://user-images.githubusercontent.com/2616517/29989263-e1545ca6-8f3f-11e7-934a-4343e48bef4b.jpg)

**Comment by SupriyaKalghatgi** [comment]
@mitramejia Thank you for pointing this out
we will update the docs accordingly

**Comment by SupriyaKalghatgi** [comment]
Check latest docs
