### ISSUE TITLE
Round corner on Card

### ISSUE THREAD

**Issue by m-maillot** [GeekyAnts/native-base-docs#57]
Hi,

I want to apply a round corner on Card component. I try with a style but style seems to be not applied to Card. Do you have any tips to do this ?

**Comment by m-maillot** [comment]
Extract themes and customized them answer to my question. I close this issue.

**Comment by harokevin** [comment]
Same. After ejecting the native-base styles to expose the default styles I changed 
``` cardBorderRadius: 2``` in `platform.js` to  ```cardBorderRadius: 10```. It gave me the rounded edge I wanted.
