### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by leenbean16** [GeekyAnts/native-base-docs#63]
Hi there. Awesome framework :)

Just wanted to let you know there is a typo on https://docs.nativebase.io/Components.html#fabs-multiple-headref

The link in the left side menu says "Muliple FABs".

Lina

**Comment by sanketsahusoft** [comment]
Can you edit the file and send a pull-request? That would really help!

Best,
Sanket

**Comment by SupriyaKalghatgi** [comment]
Check latest docs
