### ISSUE TITLE
Grid not work as aspected if nested inside <Content>-Component

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [GeekyAnts/native-base-docs#75]
Easy Grid [#57](https://github.com/GeekyAnts/react-native-easy-grid/issues/57)

**Comment by akhil-geekyants** [comment]
See commit https://github.com/GeekyAnts/native-base-docs/commit/9c4f4f10b2b08fd077afc7d8a32e86c052ac16c2

**Comment by SupriyaKalghatgi** [comment]
Check latest docs
